### ISSUE TITLE
Don't require an asterisk to send query parameters

### ISSUE THREAD

**Issue by eudoxia0** [fukamachi/myway#3]
URLs that receive query parameters shouldn't require an asterisk like "/url*" to parse them. I think this is a bug since it's not how Sinatra does it.

**Comment by fukamachi** [comment]
It is an intended behaviour since My Way router is only for matching URL path-info.
Parse URI before passing it to `connect`.

**Comment by eudoxia0** [comment]
Cool, thanks.
